[package]
name = "goblin-maker"
version = "0.3.35"
edition = "2024"

[dependencies]
asefile = "0.3.8"
macroquad = "0.4.14"
image = "0.24.9"
impl-new-derive = "0.1.3"
enum-iterator = "2.3.0"
base64 = "0.22.1"
quad-storage = "0.1.3"
quad-net = "0.1.2"
nanoserde = "0.2.1"
